# -*- coding: utf-8 -*-
"""GH_Variable Quality Assessment and Similarity Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tAejmNfhtp9vSoKdGouOwOaiiQ6d53U-
"""

#Installing libraries

!pip -q install openpyxl
!pip -q install xlsxwriter
!pip -q install missingno
!pip -q install seaborn
!pip -q install tabulate

print("="*60)
print("ALL LIBRARIES INSTALLED SUCCESSFULLY")
print("="*60)

# Importing the libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

from google.colab import files

import warnings
warnings.filterwarnings("ignore")

plt.style.use("ggplot")

print("Libraries imported successfully.")

# Uploading the excel

print("Upload the environmental dataset")

uploaded = files.upload()

excel_file = list(uploaded.keys())[0]

df = pd.read_excel(excel_file)

df.columns = df.columns.str.strip()

print("\nDataset Loaded Successfully")

print("Rows :", len(df))
print("Columns :", len(df.columns))

display(df.head())

#Definition of env variables that were extracted.

environmental_variables = [

    "Rainfall_mm_day",

    "AirTemp_°C",

    "RH_%",

    "WindSpeed_m/s",

    "SurfacePressur_hPa",

    "SoilTemp_°C",

    "Soil_pH",

    "Clay_g_per_kg",

    "Nitrogen_g_per_kg",

    "Organic_Carbon_g_per_kg"

]

print("="*70)
print("ENVIRONMENTAL VARIABLES")
print("="*70)

for i, var in enumerate(environmental_variables,1):
    print(i, var)

# DATASET INFORMATION


print("="*70)
print("DATASET INFORMATION")
print("="*70)

print()

print("Rows:",len(df))

print("Columns:",len(df.columns))

print()

display(df.dtypes)

summary = df.describe(include="all").transpose()

display(summary)

summary.to_excel("Dataset_Summary.xlsx")

files.download("Dataset_Summary.xlsx")

# CREATing OUTPUT EXCEL WORKBOOK


output_excel = "Environmental_Variable_Analysis.xlsx"

writer = pd.ExcelWriter(
    output_excel,
    engine="openpyxl"
)

print("Workbook created successfully.")

# OVERALL SUMMARY


summary_list = []

for var in environmental_variables:

    total = len(df)

    available = df[var].count()

    missing = df[var].isna().sum()

    unique = df[var].nunique()

    repeated = available - unique

    summary_list.append({

        "Variable": var,

        "Total Records": total,

        "Available": available,

        "Missing": missing,

        "Unique Values": unique,

        "Repeated Values": repeated,

        "Percent Missing":
        round((missing/total)*100,2),

        "Percent Repeated":
        round((repeated/available)*100,2)

    })

summary_df = pd.DataFrame(summary_list)

display(summary_df)

summary_df.to_excel(

    writer,

    sheet_name="Summary",

    index=False

)

# Analysis of each variable


import re

for variable in environmental_variables:

    print("="*70)
    print(variable)
    print("="*70)

    value_table = (

        df

        .groupby(variable)

        .agg(

            Frequency=(variable, "size"),

            Samples=("Sample Code",
                     lambda x: ", ".join(sorted(set(x.astype(str)))))

        )

        .reset_index()

        .sort_values(
            "Frequency",
            ascending=False
        )

    )

    value_table["Repeated"] = value_table["Frequency"] > 1

    display(value_table.head(20))

    # ----------------------------
    # Create a valid Excel sheet name
    # ----------------------------

    sheet = variable

    # Replace invalid Excel characters
    sheet = re.sub(r'[\\/*?:\[\]]', '_', sheet)

    # Excel sheet names maximum length = 31
    sheet = sheet[:31]

    value_table.to_excel(

        writer,

        sheet_name=sheet,

        index=False

    )

print("Analysis completed.")

# DESCRIPTIVE STATISTICS


stats=df[environmental_variables].describe().T

stats["Median"]=df[environmental_variables].median()

stats["Variance"]=df[environmental_variables].var()

stats["Missing"]=df[environmental_variables].isna().sum()

display(stats)

stats.to_excel(

    writer,

    sheet_name="Statistics"

)

# IDENTICAL ENVIRONMENTAL PROFILES


group_columns=environmental_variables.copy()

profiles=(

    df

    .groupby(group_columns)

    .agg(

        Number_of_Samples=("Sample Code","count"),

        Sample_Codes=("Sample Code",

                      lambda x:", ".join(sorted(set(x))))

    )

    .reset_index()

)

profiles=profiles.sort_values(

    "Number_of_Samples",

    ascending=False

)

display(profiles.head(30))

profiles.to_excel(

    writer,

    sheet_name="Identical_Profiles",

    index=False

)

# Saving workbook


writer.close()

from google.colab import files

files.download(output_excel)

print("="*70)
print("ANALYSIS COMPLETED")
print("="*70)
print("Workbook downloaded successfully.")
