# -*- coding: utf-8 -*-
"""GH_Variable_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNwn6x59-_xeYqlBwBCEwEbFnIjhZOkE
"""

# GHANA AFLATOXIN — MONTHLY MAXIMUM ENVIRONMENTAL EXTRACTION
!pip install -q earthengine-api geemap folium openpyxl
import ee
import geemap
import pandas as pd
import folium
from google.colab import files
from IPython.display import display



# Authentication of GEE
ee.Authenticate()
ee.Initialize(
    project='ee-kariukinyaga22'
)

print(
    "Earth Engine connected:",
    ee.Number(1).add(1).getInfo()
)



# Am uploading the ecel from pc files
print(
    "Upload your Excel file:"
)

uploaded = files.upload()

input_file = list(
    uploaded.keys()
)[0]

print(
    "Uploaded:",
    input_file
)

#Reading the excel and cleaning of coulumns.
original_df = pd.read_excel(
    input_file
)
original_df.columns = (
    original_df.columns
    .astype(str)
    .str.strip()

)
# Checking required columns.

required = [

    'Sample Code',
    'Year',
    'Latitude',
    'Longitude'
]

missing = [

    c
    for c in required
    if c not in original_df.columns
]
if missing:
    raise ValueError(
        "These required columns are missing: "
        + str(missing)
    )


#Creating sample table to view table.
df = original_df.copy()

# Converting the coordinates to numeric

df['Latitude'] = pd.to_numeric(
    df['Latitude'],
    errors='coerce'
)

df['Longitude'] = pd.to_numeric(
    df['Longitude'],
    errors='coerce'
)

# Converting year to numeric as well
df['Year'] = pd.to_numeric(
    df['Year'],
    errors='coerce'
)


# Remove invalid coordinates/year
df = df.dropna(
    subset=[
        'Sample Code',
        'Year',
        'Latitude',
        'Longitude'
    ]

).copy()


# Year as integer

df['Year'] = (
    df['Year']
    .astype(int)
)


# Create unique ID

df['row_id'] = range(
    len(df)
)

print(

    "\nNumber of valid samples:",
    len(df)
)



# Creating points for use in GEE


def make_feature(row):

    point = ee.Geometry.Point(

        [
            float(
                row['Longitude']
            ),

            float(
                row['Latitude']
            )
        ]
    )

    return ee.Feature(
        point,
        {
            'row_id':
            int(
                row['row_id']
            ),
            'sample_code':
            str(
                row['Sample Code']
            ),
            'year':
            int(
                row['Year']
            )
        }
    )


features = [
    make_feature(row)
    for _, row
    in df.iterrows()
]

points_fc = ee.FeatureCollection(
    features
)

print(
    "Points in Earth Engine:",
    points_fc.size().getInfo()
)


# Creating the leaflet maos to visualise points.

map_center = [
    df['Latitude'].mean(),
    df['Longitude'].mean()
]

m = folium.Map(
    location=
    map_center,
    zoom_start=6,
    tiles='OpenStreetMap'
)

# Satellite layer

folium.TileLayer(
    tiles=
    'https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
    attr='Google Satellite',
    name='Satellite',
    overlay=False,
    control=True
).add_to(m)


# Adding points to the satellite layer

for _, row in df.iterrows():
    popup = (
        f"<b>Sample Code:</b> "
        f"{row['Sample Code']}<br>"
        f"<b>Year:</b> "
        f"{row['Year']}<br>"
        f"<b>Latitude:</b> "
        f"{row['Latitude']:.6f}<br>"
        f"<b>Longitude:</b> "
        f"{row['Longitude']:.6f}"
    )


    folium.CircleMarker(
        location=[
            row['Latitude'],
            row['Longitude']
        ],

        radius=5,
        popup=folium.Popup(
            popup,
            max_width=300
        ),
        tooltip=str(
            row['Sample Code']
        ),
        fill=True
    ).add_to(m)
folium.LayerControl().add_to(
    m
)

# Displayin the map
print(
    "\nSample point map:"
)
display(m)


# Saving the  map

map_file = (
    'Ghana_Aflatoxin_Sample_Points.html'
)
m.save(
    map_file
)

# Creating 12 months for each sample code
months = [

    (1, 'January'),
    (2, 'February'),
    (3, 'March'),
    (4, 'April'),
    (5, 'May'),
    (6, 'June'),
    (7, 'July'),
    (8, 'August'),
    (9, 'September'),
    (10, 'October'),
    (11, 'November'),
    (12, 'December')
]
monthly_rows = []
for _, sample in df.iterrows():
    for month_number, month_name in months:
        monthly_rows.append(
            {

                'row_id':
                sample['row_id'],
                'Sample Code':
                sample['Sample Code'],
                'Year':
                sample['Year'],
                'Month_Number':
                month_number,
                'Month':
                month_name,
                'Latitude':
                sample['Latitude'],
                'Longitude':
                sample['Longitude']
            }
        )

monthly_df = pd.DataFrame(
    monthly_rows
)

print(
    "\nSample-month rows created:",
    len(monthly_df)
)
print(
    "Expected:",
    len(df) * 12
)


# ============================================================
# 12. CHIRPS — MAXIMUM DAILY RAINFALL
# ============================================================
#
# Dataset:
# CHIRPS Daily
#
# Output:
# Maximum daily rainfall in each month
#
# Unit:
# mm/day
#
# ============================================================

def get_rainfall(

    year,

    month

):

    start = ee.Date.fromYMD(

        int(year),

        int(month),

        1

    )


    end = start.advance(

        1,

        'month'

    )


    images = (

        ee.ImageCollection(

            'UCSB-CHG/CHIRPS/DAILY'

        )

        .filterDate(

            start,

            end

        )

        .select(

            'precipitation'

        )

    )


    monthly_max = (

        images

        .max()

        .rename(

            'Rainfall_MaxDaily_mm_day'

        )

    )


    sample_points = (

        points_fc

        .filter(

            ee.Filter.eq(

                'year',

                int(year)

            )

        )

    )


    sampled = (

        monthly_max

        .sampleRegions(

            collection=

            sample_points,

            scale=5566,

            geometries=False

        )

    )


    result = geemap.ee_to_df(

        sampled

    )


    result['Month_Number'] = int(

        month

    )


    return result



# Running rainfall extraction first mm/day


rainfall_list = []
for year in sorted(
    df['Year'].unique()

):
    for month in range(
        1,
        13
    ):
        print(
            "Rainfall:",
            year,
            month
        )
        try:
            result = get_rainfall(
                year,
                month
            )

            rainfall_list.append(
                result
            )

        except Exception as e:
            print(
                "Error:",
                e
            )

rainfall_df = pd.concat(
    rainfall_list,
    ignore_index=True
)

print(
    "\nRainfall extraction complete."
)



# Extracting all other variaboles: Air Temperature:°C
# Relative Humidity: %
# Wind Speed: m/s
# Surface Pressure:hPa
# Soil Temperature:°C

def derive_era5(
    image
):
    # Temperature
    temperature = (
        image
        .select(
            'temperature_2m'
        )
        .subtract(
            273.15
        )
        .rename(
            'AirTemp_MaxDaily_degC'
        )
    )

    # Dew point
    dewpoint = (
        image
        .select(
            'dewpoint_temperature_2m'
        )
        .subtract(
            273.15
        )

    )


    # Relative humidity
    es = (
        temperature
        .multiply(
            17.625
        )
        .divide(
            temperature.add(
                243.04
            )
        )

        .exp()
    )

    ea = (

        dewpoint

        .multiply(

            17.625
        )
        .divide(
            dewpoint.add(
                243.04
            )
        )

        .exp()
    )

    relative_humidity = (
        ea
        .divide(
            es
        )

        .multiply(
            100
        )
        .clamp(

            0,

            100
        )

        .rename(

            'RH_MaxDaily_pct'
        )

    )

    # Wind

    u = (

        image

        .select(

            'u_component_of_wind_10m'

        )

    )


    v = (

        image

        .select(

            'v_component_of_wind_10m'

        )

    )


    wind_speed = (

        u

        .pow(2)

        .add(

            v.pow(2)

        )

        .sqrt()

        .rename(

            'WindSpeed_MaxDaily_m_s'

        )

    )


    # Pressure

    pressure = (

        image

        .select(

            'surface_pressure'

        )

        .divide(

            100

        )

        .rename(

            'SurfacePressure_MaxDaily_hPa'

        )

    )


    # Soil temperature

    soil_temperature = (

        image

        .select(

            'soil_temperature_level_1'

        )

        .subtract(

            273.15

        )

        .rename(

            'SoilTemp_MaxDaily_degC'

        )

    )


    return (

        temperature

        .addBands(

            relative_humidity

        )

        .addBands(

            wind_speed

        )

        .addBands(

            pressure

        )

        .addBands(

            soil_temperature

        )

    )


# ============================================================
# 15. ERA5 MONTHLY EXTRACTION
# ============================================================

def get_era5(

    year,

    month

):

    start = ee.Date.fromYMD(

        int(year),

        int(month),

        1

    )


    end = start.advance(

        1,

        'month'

    )


    era5 = (

        ee.ImageCollection(

            'ECMWF/ERA5_LAND/HOURLY'

        )

        .filterDate(

            start,

            end

        )

        .map(

            derive_era5

        )

    )


    monthly_max = (

        era5

        .max()

    )


    sample_points = (

        points_fc

        .filter(

            ee.Filter.eq(

                'year',

                int(year)

            )

        )

    )


    sampled = (

        monthly_max

        .sampleRegions(

            collection=

            sample_points,

            scale=11132,

            geometries=False

        )

    )


    result = geemap.ee_to_df(

        sampled

    )


    result['Month_Number'] = int(

        month

    )


    return result


#ERA5 Extraction

era5_list = []


for year in sorted(

    df['Year'].unique()

):

    for month in range(

        1,

        13

    ):

        print(

            "Climate:",

            year,

            month

        )


        try:

            result = get_era5(

                year,

                month

            )


            era5_list.append(

                result

            )


        except Exception as e:

            print(

                "Error:",

                e

            )


era5_df = pd.concat(

    era5_list,

    ignore_index=True

)


print(

    "\nClimate extraction complete."

)



#  Soil variables extraction- iSDAsoil: Soil pH: pH (unitless)
# Clay:g/kg
# Nitrogen:g/kg
# Organic Carbon:g/kg

soil_assets = {

    'Soil_pH_pH_unitless':

    'ISDASOIL/Africa/v1/ph',


    'Clay_g_per_kg':

    'ISDASOIL/Africa/v1/clay_content',


    'Nitrogen_g_per_kg':

    'ISDASOIL/Africa/v1/nitrogen_total',


    'Organic_Carbon_g_per_kg':

    'ISDASOIL/Africa/v1/carbon_organic'

}


soil_images = []


for output_name, asset in soil_assets.items():

    image = ee.Image(

        asset

    )


    first_band = (

        image

        .bandNames()

        .get(0)

    )


    soil_images.append(

        image

        .select(

            [first_band],

            [output_name]

        )

    )


soil_stack = soil_images[0]


for image in soil_images[1:]:

    soil_stack = (

        soil_stack

        .addBands(

            image

        )

    )

soil_sampled = (

    soil_stack

    .sampleRegions(

        collection=

        points_fc,

        scale=30,

        geometries=False

    )

)


soil_df = geemap.ee_to_df(

    soil_sampled

)


print(

    "\nSoil extraction complete."

)



# Merging everything together


# Add rainfall

final_df = (

    monthly_df

    .merge(

        rainfall_df[

            [

                'row_id',

                'Month_Number',

                'Rainfall_MaxDaily_mm_day'

            ]

        ],

        on=[

            'row_id',

            'Month_Number'

        ],

        how='left'

    )

)


# Add climate

final_df = (

    final_df

    .merge(

        era5_df[

            [

                'row_id',

                'Month_Number',

                'AirTemp_MaxDaily_degC',

                'RH_MaxDaily_pct',

                'WindSpeed_MaxDaily_m_s',

                'SurfacePressure_MaxDaily_hPa',

                'SoilTemp_MaxDaily_degC'

            ]

        ],

        on=[

            'row_id',

            'Month_Number'

        ],

        how='left'

    )

)


# Add soil

final_df = (

    final_df

    .merge(

        soil_df[

            [

                'row_id',

                'Soil_pH_pH_unitless',

                'Clay_g_per_kg',

                'Nitrogen_g_per_kg',

                'Organic_Carbon_g_per_kg'

            ]

        ],

        on='row_id',

        how='left'

    )

)



# ADD all other ORIGINAL DATA
# This keeps your original sample information.


original_extra = original_df.copy()


original_extra.columns = (

    original_extra.columns

    .astype(str)

    .str.strip()

)


# Remove coordinates/year/sample code

columns_to_remove = [

    'Latitude',

    'Longitude',

    'Year',

    'Sample Code'

]


original_extra = (

    original_extra

    .drop(

        columns=[

            c

            for c in columns_to_remove

            if c in original_extra.columns

        ],

        errors='ignore'

    )

)


# Add row_id

original_extra['row_id'] = (

    original_extra.index

)


# Merge original sample information

final_df = (

    final_df

    .merge(

        original_extra,

        on='row_id',

        how='left'

    )

)


#sorting final

final_df = (

    final_df

    .sort_values(

        [

            'row_id',

            'Year',

            'Month_Number'

        ]

    )

    .reset_index(

        drop=True

    )

)


# REORDER COLUMNS


main_columns = [

    'row_id',

    'Sample Code',

    'Year',

    'Month_Number',

    'Month',

    'Latitude',

    'Longitude',

    'Rainfall_MaxDaily_mm_day',

    'AirTemp_MaxDaily_degC',

    'RH_MaxDaily_pct',

    'WindSpeed_MaxDaily_m_s',

    'SurfacePressure_MaxDaily_hPa',

    'SoilTemp_MaxDaily_degC',

    'Soil_pH_pH_unitless',

    'Clay_g_per_kg',

    'Nitrogen_g_per_kg',

    'Organic_Carbon_g_per_kg'

]


# Keep only columns that exist

main_columns = [

    c

    for c in main_columns

    if c in final_df.columns

]


# Other original variables

other_columns = [

    c

    for c in final_df.columns

    if c not in main_columns

]


final_df = (

    final_df[

        main_columns

        +

        other_columns

    ]

)


# FINAL DATA QUALITY CHECK


print(

    "\n=========================================="

)

print(

    "FINAL CLEAN DATASET"

)

print(

    "=========================================="

)


print(

    "Original samples:",

    len(df)

)


print(

    "Expected rows:",

    len(df) * 12

)


print(

    "Final rows:",

    len(final_df)

)


print(

    "Final columns:",

    len(final_df.columns)

)


# Check each sample has 12 months

month_check = (

    final_df

    .groupby(

        'row_id'

    )[

        'Month_Number'

    ]

    .nunique()

)


print(

    "\nSamples with exactly 12 months:",

    (

        month_check == 12

    ).sum()

)


print(

    "Samples without 12 months:",

    (

        month_check != 12

    ).sum()

)


# DISPLAY CLEAN DATASET


display(

    final_df.head(24)

)


# Exporting and downloading to pc of the file

output_file = (

    'GH_Aflatoxin_Clean_Sample_Monthly_Environmental_Data.xlsx'

)


with pd.ExcelWriter(

    output_file,

    engine='openpyxl'

) as writer:

    final_df.to_excel(

        writer,

        sheet_name='Clean_Monthly_Data',

        index=False

    )



files.download(

    output_file

)



files.download(

    map_file

)


##

print(

    "\n=========================================="

)

print(

    "DONE"

)

print(

    "=========================================="

)

print(

    "Clean Excel:",

    output_file

)

print(

    "Leaflet map:",

    map_file

)

print(

    "Rows:",

    len(final_df)

)

print(

    "Columns:",

    len(final_df.columns)

)