# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YcbalaYM-CKfrrmESYjujntB_nWrg6CC
"""

from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(dplyr)
# 
# lines <- readLines("LVB_ScopingStudy_GPS_Points_UNstructuredData.txt")
# 
# data_lines <- lines[-1]
# data_lines <- data_lines[trimws(data_lines) != ""]
# 
# split_rows <- strsplit(trimws(data_lines), "\\s{2,}")
# 
# df <- do.call(rbind, lapply(split_rows, function(x) {
#   data.frame(
#     Name      = x[1],
#     Latitude  = as.numeric(x[2]),
#     Longitude = as.numeric(x[3]),
#     Address   = ifelse(length(x) >= 4, x[4], NA),
#     stringsAsFactors = FALSE
#   )
# }))
# 
# str(df)
# head(df)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Check for any rows where lat/lon failed to parse
# df[is.na(df$Latitude) | is.na(df$Longitude), ]
# 
# # Save as clean CSV
# write.csv(df, "LVB_ScopingStudy_GPS_Points_clean.csv", row.names = FALSE)

from google.colab import files
files.download('LVB_ScopingStudy_GPS_Points_clean.csv')

